# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Genome Foundry
description: The power of automation at the service of biology
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#specify a directory to store all your collections in the same place (_drafts and _posts need to be in this directory too)
collections_dir: my_collections

#allows grouping related content into folders
collections:
  opportunities:
    #output: true # allows Jekyll to create a rendered page for each document in your collection
    sort_by: date #date is automatically assigned by Jekyll
  team:
    output: true
    # order:
    #   - vince.md
    #   - ben.md

# configures the default front matter for each type of page
defaults:
  - 
    scope:
      path: "my_collections/_opportunities"
    values:
      title: Job title
      subtitle: Job subtitle
      description: 
      application_link: mailto:GenomeFoundry@concordia.ca
      classification: Research Assistant under the CARE union at Concordia University
      salary: $27.37/hr
      hours: 35
      duration: 1 year, renewable
      startDate: as of August 2022
      supervisor: Dr. Vincent Martin
      location: |- # this means to ignore newlines until "unit:"
          7141 Sherbrooke St West, GE building,  
          Montreal, QC, H4B 1R6
      unit: |-
          Centre for Applied Synthetic Biology at  
          Concordia University
  # - scope:
  #     path: ""
  #     type: "team"
  #   values:
  #     layout: "team"

# activate the following plugins
plugins:
  - autoprefixer-rails #needed for bootstrap sass compiling 
  - jekyll-assets #image management https://github.com/envygeeks/jekyll-assets

#The jekyll-autoprefixer plugin can then be configured under the autoprefixer keyword
autoprefixer:
  #configure prefixes to support the last four versions of each browser
  browsers:
    - "last 4 versions"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
